- name: Update the apt package index again
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker Compose using pip
  pip:
    name: docker-compose

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes

- name: Se connecter au registre Docker avec un token d'accès personnel
  shell: echo "{{ docker_token }}" | docker login testGIThubFormation --password-stdin registry.gitlab.com

- name: Run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
